name: Build Linux

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          check-latest: true

      - name: Build Linux binary
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build ./...
